name: CI

on:
  push:
    branches: [ main ]
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Install clojure tools-deps
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: 1.10.1.693
          
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run tests
        run: |
          yarn install
          yarn test
